name: Build & Deploy Lit Review + Notes

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: '3.1.11'

      - name: Prepare includes
        run: |
          mkdir -p build/includes
          # Banner on the main review page
          cat > build/includes/review-nav.html <<'HTML'
          <nav style="background:#f6f8fa;border-bottom:1px solid #e5e7eb;padding:12px 16px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif">
            <a href="./notes-html/index.html" style="text-decoration:none;font-weight:600">Reading notes</a>
          </nav>
          HTML
          # Top link on note pages
          cat > build/includes/note-nav.html <<'HTML'
          <nav style="background:#f6f8fa;border-bottom:1px solid #e5e7eb;padding:12px 16px;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif">
            <a href="../review.html" style="text-decoration:none">← Back to Literature Review</a>
            &nbsp;&middot;&nbsp;
            <a href="./index.html" style="text-decoration:none">All notes</a>
          </nav>
          HTML
          # Footer with last-updated
          echo "<footer style='margin-top:2rem;padding-top:1rem;border-top:1px solid #ddd;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;font-size:0.9rem;color:#555;'>Last updated $(date '+%d %B %Y')</footer>" > build/includes/footer.html

      - name: Build review.html
        run: |
          mkdir -p build
          pandoc notes/review.md \
            --from=markdown \
            --to=html5 \
            --citeproc \
            --bibliography=refs/library.bib \
            --csl=refs/apa.csl \
            --metadata reference-section-title="References" \
            --metadata link-citations=true \
            --metadata title="Literature Review" \
            --metadata date="Last updated $(date '+%d %B %Y')" \
            --standalone \
            --include-before-body=build/includes/review-nav.html \
            --include-after-body=build/includes/footer.html \
            -o build/review.html

      - name: Build reading notes → HTML
        run: |
          mkdir -p build/notes-html
          shopt -s nullglob
          for f in notes/reading-notes/*.md; do
            base="$(basename "$f")"
            [ "$base" = "template.md" ] && continue
            out="build/notes-html/${base%.md}.html"
            pandoc "$f" \
              --from=markdown \
              --to=html5 \
              --standalone \
              --citeproc \
              --bibliography=refs/library.bib \
              --csl=refs/apa.csl \
              --metadata reference-section-title="References" \
              --metadata link-citations=true \
              --metadata date="Last updated $(date '+%d %B %Y')" \
              --include-before-body=build/includes/note-nav.html \
              --include-after-body=build/includes/footer.html \
              -o "$out"
          done

      - name: Create notes index
        run: |
          NOTES_DIR="build/notes-html"
          mkdir -p "$NOTES_DIR"
          {
            echo "<!doctype html><meta charset='utf-8'><title>Reading Notes</title>"
            echo "<main style='max-width:860px;margin:2rem auto;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif'>"
            echo "<h1 style='margin-bottom:1rem'>Reading Notes</h1><ul>"
            for f in "$NOTES_DIR"/*.html; do
              [ -e "$f" ] || continue
              file=$(basename "$f")
              [ "$file" = "index.html" ] && continue
              title=$(sed -n 's/.*<title>\(.*\)<\/title>.*/\1/p' "$f" | head -1)
              [ -z "$title" ] && title="${file%.html}"
              echo "<li><a href='./$file'>$title</a></li>"
            done
            echo "</ul>"
            echo "<p style='margin-top:2rem'><a href='../review.html'>&larr; Back to Literature Review</a></p>"
            echo "</main>"
          } > "$NOTES_DIR/index.html"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4