name: Build & Deploy (Pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Setup Pandoc (stable)
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'  # stable, includes citeproc

      - name: Tool versions
        run: |
          set -eux
          pandoc -v | head -n 2
          python3 --version
          lua -v || true

      - name: Build site
        run: |
          set -euxo pipefail
          chmod +x scripts/build-notes.sh
          ./scripts/build-notes.sh

      - name: List build output
        run: |
          set -eux
          echo "::group::notes-html"
          ls -lah notes-html
          echo "::endgroup::"
          test -f notes-html/index.html
          test -f notes-html/review.html

      - name: Sanity check references
        run: |
          set -eux
          ! grep -q 'Lee, J. (2018)' notes-html/review.html
          ! grep -q 'Smith, J. (2020)' notes-html/review.html

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: notes-html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4